name: itbg
favicon: null
layout_spectrum: 0.9180104285478592
typography_spectrum: 0.6267138789407909
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.10923719010315835
  lightness: 0.9958848564419895
  saturation: 0.7480034448672086
  rhythmicContrast: 0.5017491523176432
purpose: []
